"""session table

Revision ID: a988fbf8cca5
Revises: 
Create Date: 2020-08-09 04:32:19.605155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a988fbf8cca5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('resource', 'chapter',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_resource_chapter'), 'resource', ['chapter'], unique=True)
    op.add_column('session', sa.Column('marks', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session', 'marks', ['marks'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'marks')
    op.drop_index(op.f('ix_resource_chapter'), table_name='resource')
    op.alter_column('resource', 'chapter',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('marks')
    # ### end Alembic commands ###
